- name: install nginx
  yum: name=nginx state=present

- name: create www directory
  file: >
    path=/var/www
    owner={{ rbenv_user }}
    group={{ rbenv_user }}
    mode=0775
    recurse=yes
    state=directory

- name: create project directory
  file: >
    path=/var/www/{{ project_domain }}/log
    owner={{ rbenv_user }}
    group={{ rbenv_user }}
    mode=0775
    recurse=yes
    state=directory

- name: create sysconfig/nginx
  copy: src=sysconfig.nginx dest=/etc/sysconfig/nginx

- name: make nginx log directory
  file: >
    path=/var/log/nginx
    owner=nginx
    group={{ rbenv_user }}
    mode=0775
    state=directory

- name: make nginx project log directory
  file: >
    path=/var/log/nginx/{{ project_domain }}
    owner=nginx
    group={{ rbenv_user }}
    mode=0775
    state=directory

- name: nginx default config
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0644
  notify:
    - reload nginx

- name: nginx project config
  template: >
    src={{ project_domain }}.conf.j2
    dest=/etc/nginx/conf.d/{{ project_domain }}.conf
    owner=root
    group=root
    mode=0644
  notify:
    - reload nginx

- name: start nginx service
  service: name=nginx state=started enabled=yes

